@startuml
!theme plain
allowmixing

package "view" {
    class "MainClass" as MainClass
}

package "DAO" {
    class "DataSource" as DataSource
    class "ClienteDAO" as ClienteDAO
}

package "model" {
    class "Cliente" as Cliente {
        + nome: String
        - void method()
    }
}

component "Banco de Dados" as BD <<Database>>

MainClass --> DAO
DAO --> DataSource
DAO --> ClienteDAO
ClienteDAO --> Cliente : usa
DataSource --> BD : conecta\n(jdbc)

@enduml
